### ISSUE TITLE
Text element positioning when rendering to a canvas

### ISSUE THREAD

**Issue by bkkcoins** [borgar/svglib#3]
I've found that text elements are not positioned correctly when I render an svg document onto a RLG canvas. I have fixed it for my own use but I don't understand why it's coded as is and expect it must work for the more typical examples provided. 

My code fragment looks like this,
```
    ...
    pg = Canvas("paperwallet.pdf", pagesize=(pgW,pgH))
    dX = dY = 0
    ...
    doc = xml.dom.minidom.parseString(data)
            svgRenderer = SvgRenderer()
            svgRenderer.render(doc.documentElement)
            renderPDF.draw(svgRenderer.finish(), pg, dX, dY)
    ...
```
In the convertText function in svglib.py line 870 there is,
```
    gr.translate(0, -2*y)
```
I corrected my problem by restoring the translate to -1 instead of -2. I'm not sure why this happens but -1 makes sense to me. If there is some co-ordinates difference between various ways of using svglib, then maybe a init argument could be used to set what type of text co-ords should be used. I'd be happy to code that for a pull request but would first like to know why -2 is used generally.

**Comment by borgar** [comment]
I am not the maintainer of this project. It is simply here to allow people to access my `text-fixes` branch. I am not accepting pull requests, those should be directed at the actual project repo: <https://bitbucket.org/deeplook/svglib>
